sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tEAv843RHPPkKuzjaYa
    access-key-secret: 5fMti4p1EZXDfTgtEq14SW8dAEV0MF
    bucket-name: sky-out-f
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxa4685c7fcaff97a0
    secret: 897e4b5e66f622f0c68ecebaf28d0569

